# generated by datamodel-codegen:
#   filename:  card_info.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CardType(StrEnum):
    """
    Whether the card is professionally graded/slabbed or raw (loose).
    """

    graded = 'graded'
    raw = 'raw'


class Sport(StrEnum):
    """
    Sport the card belongs to (football = American football).
    """

    baseball = 'baseball'
    basketball = 'basketball'
    football = 'football'
    hockey = 'hockey'
    soccer = 'soccer'
    other = 'other'


class Attributes(BaseModel):
    """
    Card attribute flags and serial-numbering info.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rookie: bool | None = False
    """
    Rookie card (RC).
    """
    serial_number: str | None = None
    """
    For a serial-numbered (limited) card such as '07/99', this copy's own number (the 07). Shows which copy this is out of the print run — NOT the card's number within the set.
    """
    serial_limit: str | None = None
    """
    For a serial-numbered (limited) card such as '07/99', the total print run / population (the 99).
    """
    serial_matches_jersey_number: bool | None = None
    """
    True when the copy's serial number equals the player's jersey number (e.g. 07/99 for a player wearing #7) — such 'jersey-numbered' copies are rarer/more valuable. Null if unknown.
    """


class Photo(BaseModel):
    """
    Visual details of the player's picture printed on the card.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    jersey_colors: list[str] | None = None
    """
    Colors of the jersey the player is wearing in the card's picture, if visible (e.g. ['red','black','white']).
    """
    jersey_number: str | None = None
    """
    Best guess for the number on the jersey in the card's picture, if visible (as printed, e.g. '23').
    """
    jersey_number_candidates: list[str] | None = None
    """
    If the jersey number is uncertain (partially visible/occluded), all plausible candidates, best first (e.g. ['8','3']). Null/empty when jersey_number is confident or not visible.
    """


class Autograph(BaseModel):
    """
    Autograph/signature details.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    present: bool | None = None
    """
    Does the card contain an autograph? Null if unknown.
    """
    ink_color: str | None = None
    """
    Color of the signature ink (e.g. 'black', 'blue', 'gold', 'silver'). Black is the standard; any other color is rarer/more valuable.
    """


class PieceType(StrEnum):
    """
    Kind of embedded memorabilia piece.
    """

    patch = 'patch'
    jersey = 'jersey'
    ball = 'ball'
    floor = 'floor'
    shoe = 'shoe'
    other = 'other'


class MemorabiliaPiece(BaseModel):
    """
    One embedded memorabilia piece. A card can contain several.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: PieceType | None = None
    """
    Kind of piece: patch (multi-color jersey patch), jersey (plain jersey swatch), ball, floor, shoe, or other.
    """
    is_fabric: bool | None = None
    """
    Is it an actual piece of fabric/material (true) vs a printed/manufactured facsimile (false)? Null if unclear.
    """
    colors: list[str] | None = None
    """
    Distinct colors visible in the piece (e.g. ['wine','white','gold']).
    """
    unique_color_count: Annotated[int | None, Field(ge=0)] = None
    """
    Number of unique colors in the piece (more colors usually = rarer patch).
    """
    contains_team_logo_part: bool | None = None
    """
    Does the piece contain part of the team logo? Null if unclear.
    """
    contains_player_name_part: bool | None = None
    """
    Does the piece contain part of the player's name (nameplate letters)? Null if unclear.
    """
    contains_team_name_part: bool | None = None
    """
    Does the piece contain part of the team name lettering? Null if unclear.
    """
    letters_visible: str | None = None
    """
    Any letters/characters visible in the piece, as read (e.g. 'AME'). Null if none.
    """


class Memorabilia(BaseModel):
    """
    Embedded memorabilia in the card/slab. 'pieces' lists each embedded piece (can be more than one).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    present: bool | None = None
    """
    Does the card contain memorabilia? Null if unknown.
    """
    pieces: Annotated[list[MemorabiliaPiece] | None, Field(validate_default=True)] = []
    """
    Each embedded piece, analyzed individually.
    """


class Subgrades(BaseModel):
    """
    Per-aspect subgrades (e.g. BGS).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    centering: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    corners: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    edges: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    surface: Annotated[float | None, Field(ge=0.0, le=10.0)] = None


class GradingCompany(StrEnum):
    """
    Grading company. BGS = Beckett Grading Services.
    """

    PSA = 'PSA'
    BGS = 'BGS'
    SGC = 'SGC'
    CGC = 'CGC'
    TAG = 'TAG'
    other = 'other'


class GradedInfo(BaseModel):
    """
    Details read from a graded slab label and/or verified via a cert API.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grading_company: GradingCompany | None = None
    """
    Grading company. BGS = Beckett Grading Services.
    """
    grade: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    """
    Numeric grade, e.g. 10 or 9.5.
    """
    grade_label: str | None = None
    """
    Grade label as printed, e.g. 'GEM-MT 10'.
    """
    description: str | None = None
    """
    The descriptive information line(s) from the graded label (year/brand/set/player/card# as the grader printed them).
    """
    subgrades: Subgrades | None = None
    autograph_grade: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    """
    Separate autograph grade printed on some labels (e.g. BGS 'AUTOGRAPH 10'), distinct from the card grade.
    """
    cert_number: str | None = None
    """
    Certification/serial number on the slab.
    """
    label_text: str | None = None
    """
    Full raw OCR of the label, for reference.
    """


class Engine(StrEnum):
    """
    Which engine produced this.
    """

    claude = 'claude'
    on_device = 'on_device'


class Provenance(BaseModel):
    """
    Where/how this record was produced.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    engine: Engine
    """
    Which engine produced this.
    """
    model_version: str
    """
    Model id (e.g. 'claude-opus-4-8') or app build.
    """
    timestamp: AwareDatetime
    """
    ISO-8601 timestamp.
    """
    source_images: list[str] | None = []
    """
    References/hashes of the input image(s) — front and back.
    """


class CardInfo(BaseModel):
    """
    Canonical structured record for a sports card extracted by either engine (Claude API or on-device). Inputs are BOTH sides of the card (front + back). Single source of truth; Pydantic and Kotlin types are generated from this file. Extraction hint: year, brand, set and subset are most often printed at the bottom of the card front, and on the label if graded. NOTE: when card_type is 'graded', the 'graded' object should be present (may contain nulls if unreadable).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    card_type: CardType
    """
    Whether the card is professionally graded/slabbed or raw (loose).
    """
    sport: Sport | None = None
    """
    Sport the card belongs to (football = American football).
    """
    player_name: str | None = None
    """
    Subject/athlete name as printed.
    """
    year: str | None = None
    """
    Card year or season, e.g. '2003' or '2003-04'. Often printed at the bottom of the card and on the graded label.
    """
    brand: str | None = None
    """
    Card brand/maker (Topps, Panini, Upper Deck, Bowman, Fleer, ...), normalized. Often printed at the bottom of the card and on the graded label.
    """
    set: str | None = None
    """
    Product/set name, normalized. Often printed at the bottom of the card and on the graded label.
    """
    subset: str | None = None
    """
    Insert/subset name, if any. Often printed at the bottom of the card and on the graded label.
    """
    parallel: str | None = None
    """
    Parallel/variation, e.g. 'Silver Prizm'.
    """
    card_number: str | None = None
    """
    The card's number WITHIN the set, as printed (e.g. '#250', 'RC-12'). NOT the serial/print-run numbering like 5/30 — that goes in attributes.serial_number/serial_limit.
    """
    team: str | None = None
    """
    Player's team/franchise name, if present.
    """
    language: str | None = None
    """
    ISO language code if detectable.
    """
    attributes: Attributes
    photo: Photo | None = None
    """
    Visual details of the player's picture printed on the card.
    """
    autograph: Autograph | None = None
    """
    Autograph/signature details.
    """
    memorabilia: Memorabilia | None = None
    """
    Embedded memorabilia details (patch/ball/floor/jersey/shoe pieces). There can be more than one piece in a card.
    """
    graded: GradedInfo | None = None
    """
    Grading details; present when card_type is 'graded'.
    """
    per_field_confidence: dict[str, float]
    """
    Confidence in [0,1] for individual fields, keyed by field name (dot-paths allowed, e.g. 'autograph.ink_color').
    """
    provenance: Provenance
    raw_output: dict[str, Any] | None = None
    """
    Raw engine output (OCR text or model JSON) for debugging.
    """
