# generated by datamodel-codegen:
#   filename:  card_info.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CardType(StrEnum):
    """
    Whether the card is professionally graded/slabbed or raw (loose).
    """

    graded = 'graded'
    raw = 'raw'


class Sport(StrEnum):
    """
    Sport the card belongs to.
    """

    baseball = 'baseball'
    basketball = 'basketball'
    football = 'football'
    hockey = 'hockey'
    soccer = 'soccer'
    other = 'other'


class Photo(BaseModel):
    """
    Visual details of the player's picture printed on the card.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    jersey_colors: list[str] | None = None
    """
    Colors of the jersey the player is wearing in the card's picture, if visible (e.g. ['red','black','white']).
    """
    jersey_number: str | None = None
    """
    Number shown on the jersey in the card's picture, if visible (as printed, e.g. '23').
    """


class Relic(BaseModel):
    """
    Details of an embedded memorabilia/relic piece (e.g. a real jersey swatch) in the card/slab.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    swatch_colors: list[str] | None = None
    """
    Colors of the embedded real-life jersey/memorabilia piece, if present (e.g. ['blue','white']).
    """


class Attributes(BaseModel):
    """
    Card attribute flags and serial-numbering info.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rookie: bool | None = False
    """
    Rookie card (RC).
    """
    autograph: bool | None = False
    """
    Contains an autograph.
    """
    relic: bool | None = False
    """
    Contains a relic/memorabilia/patch.
    """
    serial_number: str | None = None
    """
    For a serial-numbered (limited) card such as '5/30', this card's own number (the 5).
    """
    serial_limit: str | None = None
    """
    For a serial-numbered (limited) card such as '5/30', the total print run/population (the 30).
    """


class Subgrades(BaseModel):
    """
    Per-aspect subgrades (e.g. BGS).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    centering: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    corners: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    edges: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    surface: Annotated[float | None, Field(ge=0.0, le=10.0)] = None


class GradingCompany(StrEnum):
    """
    Grading company. BGS = Beckett Grading Services.
    """

    PSA = 'PSA'
    BGS = 'BGS'
    SGC = 'SGC'
    CGC = 'CGC'
    TAG = 'TAG'
    other = 'other'


class GradedInfo(BaseModel):
    """
    Details read from a graded slab label and/or verified via a cert API.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grading_company: GradingCompany | None = None
    """
    Grading company. BGS = Beckett Grading Services.
    """
    grade: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    """
    Numeric grade, e.g. 10 or 9.5.
    """
    grade_label: str | None = None
    """
    Grade label as printed, e.g. 'GEM-MT 10'.
    """
    subgrades: Subgrades | None = None
    cert_number: str | None = None
    """
    Certification/serial number on the slab.
    """
    label_text: str | None = None
    """
    Full OCR of the label, for reference.
    """


class Engine(StrEnum):
    """
    Which engine produced this.
    """

    claude = 'claude'
    on_device = 'on_device'


class Provenance(BaseModel):
    """
    Where/how this record was produced.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    engine: Engine
    """
    Which engine produced this.
    """
    model_version: str
    """
    Model id (e.g. 'claude-opus-4-8') or app build.
    """
    timestamp: AwareDatetime
    """
    ISO-8601 timestamp.
    """
    source_images: list[str] | None = []
    """
    References/hashes of the input image(s).
    """


class CardInfo(BaseModel):
    """
    Canonical structured record for a sports card extracted by either engine (Claude API or on-device). Single source of truth; Pydantic and Kotlin types are generated from this file. NOTE: when card_type is 'graded', the 'graded' object should be present (may contain nulls if unreadable).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    card_type: CardType
    """
    Whether the card is professionally graded/slabbed or raw (loose).
    """
    sport: Sport | None = None
    """
    Sport the card belongs to.
    """
    player_name: str | None = None
    """
    Subject/athlete name as printed.
    """
    year: str | None = None
    """
    Card year or season, e.g. '2003' or '2003-04'.
    """
    manufacturer: str | None = None
    """
    Card maker (Topps, Panini, Upper Deck, Bowman, Fleer, ...), normalized.
    """
    set: str | None = None
    """
    Product/set name, normalized.
    """
    subset: str | None = None
    """
    Insert/subset name, if any.
    """
    parallel: str | None = None
    """
    Parallel/variation, e.g. 'Silver Prizm'.
    """
    card_number: str | None = None
    """
    Card number exactly as printed, e.g. 'RC-12' or '#250'.
    """
    team: str | None = None
    """
    Team/franchise, if present.
    """
    language: str | None = None
    """
    ISO language code if detectable.
    """
    attributes: Attributes
    photo: Photo | None = None
    """
    Visual details of the player's picture printed on the card.
    """
    relic: Relic | None = None
    """
    Embedded memorabilia/relic details; present for relic ('jersey piece') cards.
    """
    graded: GradedInfo | None = None
    """
    Grading details; present when card_type is 'graded'.
    """
    per_field_confidence: dict[str, float]
    """
    Confidence in [0,1] for individual fields, keyed by field name.
    """
    provenance: Provenance
    raw_output: dict[str, Any] | None = None
    """
    Raw engine output (OCR text or model JSON) for debugging.
    """
